// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Joka Beatz shop catalog (beat packs, drum kits, presets, etc.) by name, category, or free-text query. Returns up to 20 products with name, slug, price, category, and shop URL.",
  inputSchema: {
    query: z.string().optional().describe("Text to match against product name/description."),
    category: z.string().optional().describe("Filter by category slug or name."),
    limit: z.number().int().positive().optional().describe("Max results (default 20, hard cap 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const cap = Math.min(limit ?? 20, 50);
    let q = sb.from("products").select("id, name, slug, price, category, description, active").eq("active", true).limit(cap);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.ilike("category", `%${category}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((p) => ({
      name: p.name,
      price: p.price,
      category: p.category,
      url: `https://jokabeatz.com/shop/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, products: rows }
    };
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_orders_default = defineTool2({
  name: "list_recent_orders",
  title: "List recent orders",
  description: "List the most recent shop orders (admin only; RLS restricts non-admin callers to their own orders). Returns id, customer email, total, status, and created_at.",
  inputSchema: {
    limit: z2.number().int().positive().optional().describe("Max rows (default 20, cap 100)."),
    status: z2.string().optional().describe("Filter by status (e.g. paid, pending).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const cap = Math.min(limit ?? 20, 100);
    let q = sb.from("orders").select("id, user_id, product_id, amount, status, created_at").order("created_at", { ascending: false }).limit(cap);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published Joka Beatz blog posts, newest first. Returns title, slug, excerpt, and public URL.",
  inputSchema: {
    query: z3.string().optional().describe("Match against post title."),
    limit: z3.number().int().positive().optional().describe("Max results (default 10, cap 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser3(ctx);
    const cap = Math.min(limit ?? 10, 50);
    let q = sb.from("blog_posts").select("title, slug, excerpt, published_at, status").eq("status", "published").order("published_at", { ascending: false }).limit(cap);
    if (query) q = q.ilike("title", `%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((p) => ({
      title: p.title,
      excerpt: p.excerpt,
      published_at: p.published_at,
      url: `https://jokabeatz.com/blog/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, posts: rows }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_leads_default = defineTool4({
  name: "list_leads",
  title: "List email leads",
  description: "List the most recent email leads captured across the site (admin only via RLS). Returns email, name, source page, and created_at.",
  inputSchema: {
    limit: z4.number().int().positive().optional().describe("Max rows (default 25, cap 200)."),
    source: z4.string().optional().describe("Filter by source_page substring.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, source }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const cap = Math.min(limit ?? 25, 200);
    let q = sb.from("leads").select("email, name, source_page, created_at").order("created_at", { ascending: false }).limit(cap);
    if (source) q = q.ilike("source_page", `%${source}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { count: data?.length ?? 0, leads: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sxykbgwwxkktrsnghyjp";
var mcp_default = defineMcp({
  name: "joka-beatz-mcp",
  title: "Joka Beatz",
  version: "0.1.0",
  instructions: "Tools to browse the Joka Beatz beat shop, blog, orders, and free-beat leads. Callers act as the signed-in Joka Beatz user; admin-only data (orders, leads) requires an admin account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, list_recent_orders_default, list_blog_posts_default, list_leads_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
